### ISSUE TITLE
Concurrent features in the same client instance

### ISSUE THREAD

**Issue by HerrRomich** [hazelcast/hazelcast-nodejs-client#290] opened 2018-03-29 13:08 UTC
My node.js service should set a lock to a specific element in hazelcast.map. 
If service processes a number of requests this lock should be concurrent among requests. 
Unfortunately, if I use for locking the same Hazelcast.client (the same connection to server) the concurrency is not supported, because the method getMap() returns the same Map Instance. 
I would like to have an overloaded Method getMap with threadId parameter, to avoid unnecessary multiple connection to Hazelcast Server as a workaround.
The same overloaded method I would like to have for all concurrent features, like Lock, etc.

Thank you

**Comment by mustafaiman** [comment] 2018-04-18 20:17
@HerrRomich 
What I understand from your use case is that you need non-reentrant locking instead of re-entrant locks that we provide. You do not want one Node.js client to acquire the same lock a second time. Is my understanding correct?

This feels like you are trying to implement a locking mechanism within the boundaries of a single node.js process. Given that there is no threading in Node.js, I strongly think that one should not need a concurrency primitive within the boundary of only one node.js process. Instead, you should be able to use simple flags combined with callbacks or promises. Would you like to elaborate more on your problem so we can have a better idea why such mechanism is useful to implement?

If I did not understand your request correctly, would you care to elaborate with maybe some sample code?

**Comment by HerrRomich** [comment] 2018-04-21 16:32
Hi Mustafa,
thank you for you answer.
May be should explain my case more carefully. Your suggestion is good, but have some weaknesses in implementation. 
First of all my service process requests listening a message queue.  To complete the processing of date this service requests additional info over messaging queue from another service, that also hosts in my cloud. Before I send this second request (that could take some time by second service) I would like to check cache (hazelcast map). If there is nothing in cache for my key, I set a lock in map thor this key and sends request to second service.
The map has retention period 10 minutes.
If another request comes to my first service and will need an lnfo from coach according to the same key, it should wait until the previous request is processed, info is cached and lock is unset. After that the second request will be processed with a fresh value from cache. 
Moreover it should be possible to have so many instances of both services as I wish.
That is my case.
If you have another suggestion or if you could implement the overloaded method I would appreciate you.

**Comment by mustafaiman** [comment] 2018-04-23 19:51
Your use-case seems like a NearCache use case. Its inner workings is not exactly like you describe. It may make multiple requests for the same key if there are multiple requests until the first one is resolved. This is a little overhead. However, taking a cluster-wide lock for each request is going to hit the performance worse. If retention period is 10 minutes, I think overhead of a few redundant requests are negligible. Plus, that is a price that you have to pay because network is not reliable. It is not guaranteed that your first request receives a response before your second one.

To implement the exact mechanism you described, you need to add an `outstandingRequests` queue per client instance. Then you consult both cluster-wide lock and the outstanding requests each time.

**Comment by mustafaiman** [comment] 2018-07-05 09:57
I am closing the issue as this is not a bug report. You are welcome to use our gitter channel for getting help anytime: https://gitter.im/hazelcast/hazelcast-nodejs-client

**Closed by mustafaiman** 2018-07-05 09:57 UTC
Labels: Type: Enhancement
