### ISSUE TITLE
Deprecation Warnings: Bluebird Promises

### ISSUE THREAD

**Issue by awill1988** [hazelcast/hazelcast-nodejs-client#251] opened 2018-01-31 08:25 UTC
#### Description
Using the client as it is today, the stdout is littered with deprecation warnings whilst connected to my hazelcast instance.

#### Troubleshooting & Proposed Resolutions
- I consulted the bluebird.js website for [migration guidance](http://bluebirdjs.com/docs/api/deferred-migration.html), created a `utils/PromiseUtil.ts` that plays nicely with Typescript (I'm "team typescript" btw 😄 👍 )
- Additionally, there was a runaway promise warning in `invocation/ClusterService.ts` so I fixed that again with [guidance from bluebird.js](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it)
- I have forked the project and [contributed my commits here](https://github.com/awill1988/hazelcast-nodejs-client/commits/feature/update-promises)

#### My package.json versions
- **hazelcast-client:** latest
- **node:** Carbon LTS (v8.9.4)
- **bluebird:** 3.5.1

Would be honored to be added as a contributor, then I can create an official pull request. Or if you prefer to copy and paste my commits, I'm not worried about it--just looking to help out and use the awesome software you guys are making 🔥 💯 .

Thanks,
Adam W.

**Comment by mustafaiman** [comment] 2018-02-12 14:15
Thanks @awill1988 . Your effort is very much appreciated. We adopted deferreds in the first place because they are faster than standard Promise api. We need to consider the performance impact of these changes first. I am a bit hesitant to do this change because of possible performance degredation. Bluebird deciding to litter the output at every promise operation is unfortunate.

About the runaway promise part, that's a good catch. You can actually create a PR to fix just that while we decide what to do about deferreds. I am not sure what you are referring to by adding as a contributor but we would like to merge your PR. Your commit will be in the commit history and https://github.com/hazelcast/hazelcast-nodejs-client/graphs/contributors should automatically list you after your PR is merged.

We need external contributors to sign [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement)

Looking forward to your PR.

**Comment by duncankmckinnon** [comment] 2018-08-27 19:36
Is there an existing workaround or solution for this?  We're getting logs full of promise.defer deprecation warnings

**Comment by mustafaiman** [comment] 2018-08-30 19:39
@duncankmckinnon Unfortunately, we have no workaround for this right now. Thanks for bringing this up again. I do not know if we can address this problem in the current release yet. I will discuss this with the team and update the issue with information.

**Comment by skamv** [comment] 2018-09-07 10:19
I am also having this Deprecation Warnings all over my logs

**Comment by manoojm** [comment] 2018-09-25 08:57
This shows up all over the console. Please fix this ASAP.
(node:9080) Warning: Promise.defer is deprecated and will be removed in a future version. Use new Promise instead.

**Comment by furkansenharputlu** [comment] 2018-11-07 14:59
Hi all,
I created a new example project and added Hazelcast Node.js client 0.9 version as dependency. I wrote a simple map example but I don't see any Deprecation Warning. Can you explain to me how I can reproduce the warnings ?

**Comment by manoojm** [comment] 2018-11-11 10:10
I guess a simple map example won't help in reproducing this. I am running with 0.9v in my nodejs project and can see the warnings repeatedly on the console. At this moment I am not sure how I can reproduce it in a standalone program.. May be u can try creating/integrating the Hazelcast client into a react router app backed with nodejs for storing user session or some such info and keep the server running ..

**Closed** 2018-11-21 09:20 UTC
Labels: Type: Critical
