### ISSUE TITLE
fails compilation in TypeScript project if tsconfig: strictNullChecks is true

### ISSUE THREAD

**Issue by zachlysobey** [hazelcast/hazelcast-nodejs-client#310] opened 2018-06-28 18:11 UTC
It seems that the TS types used here break ts compilation if strictNullChecks is true.

I'm happy to take a stab at a PR *fix*-ing these types, but wanted to check in first and make sure I'm not thinking about this wrong.

```
node_modules/hazelcast-client/lib/core/MapListener.d.ts(2,5): error TS2411: Property 'added' of type 'EntryEventListener<K, V> | undefined' is not assignable to string index type 'EntryEventListener<K, V>'.
node_modules/hazelcast-client/lib/core/MapListener.d.ts(3,5): error TS2411: Property 'removed' of type 'EntryEventListener<K, V> | undefined' is not assignable to string index type 'EntryEventListener<K, V>'.
node_modules/hazelcast-client/lib/core/MapListener.d.ts(4,5): error TS2411: Property 'updated' of type 'EntryEventListener<K, V> | undefined' is not assignable to string index type 'EntryEventListener<K, V>'.
node_modules/hazelcast-client/lib/core/MapListener.d.ts(5,5): error TS2411: Property 'merged' of type 'EntryEventListener<K, V> | undefined' is not assignable to string index type 'EntryEventListener<K, V>'.
node_modules/hazelcast-client/lib/core/MapListener.d.ts(6,5): error TS2411: Property 'evicted' of type 'EntryEventListener<K, V> | undefined' is not assignable to string index type 'EntryEventListener<K, V>'.
node_modules/hazelcast-client/lib/core/MapListener.d.ts(7,5): error TS2411: Property 'evictedAll' of type 'EntryEventListener<K, V> | undefined' is not assignable to string index type 'EntryEventListener<K, V>'.
node_modules/hazelcast-client/lib/core/MapListener.d.ts(8,5): error TS2411: Property 'clearedAll' of type 'EntryEventListener<K, V> | undefined' is not assignable to string index type 'EntryEventListener<K, V>'.
node_modules/hazelcast-client/lib/ListenerService.d.ts(24,5): error TS2416: Property 'onHeartbeatRestored' in type 'ListenerService' is not assignable to the same property in base type 'ConnectionHeartbeatListener'.
  Type '(connection: ClientConnection) => void' is not assignable to type '((connection?: ClientConnection | undefined) => void) | undefined'.
    Type '(connection: ClientConnection) => void' is not assignable to type '(connection?: ClientConnection | undefined) => void'.
      Types of parameters 'connection' and 'connection' are incompatible.
        Type 'ClientConnection | undefined' is not assignable to type 'ClientConnection'.
          Type 'undefined' is not assignable to type 'ClientConnection'.
```

**Comment by srknzl** [comment] 2021-03-17 14:35
Seems like there is not any option to exclude certain folder just for single rule. Closing this as this is duplicate of #817. The pr #817 implements all flags but `strictNullChecks`. It needs a change to codec generator, so I postponed it for now

**Closed by srknzl** 2021-03-17 14:35 UTC
Labels: Priority: Low, Type: Enhancement
