### ISSUE TITLE
Race condition with locks when a CP session hasn't been issued yet

### ISSUE THREAD

**Issue by aetheryx** [hazelcast/hazelcast-nodejs-client#898] opened 2021-05-16 23:05 UTC
**Describe the bug**
When an application tries to concurrently try to acquire a lock with no prior CP session, releasing the lock throws a LockOwnershipLostError.

**Expected behavior**
Applications can concurrently try to acquire locks without needing to kickstart a CP session.

**Environment (please complete the following information):**

1. Exact Node.js client version that you use: v4.1.0

2. Exact Hazelcast version that you use: 4.2

3. Cluster size, _i.e._ the number of Hazelcast cluster members: 1

4. Number of clients: 1

5. Java version (no extra JVM parameters):
```
openjdk 11.0.9 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-alpine-r1)
OpenJDK 64-Bit Server VM (build 11.0.9+11-alpine-r1, mixed mode)
```

6. Node.js version: v16.1.0

7. Operating system: Node.js on Arch Linux 5.11, Hazelcast on Alpine 5.11 (through docker, `hazelcast/hazelcast`)

**To Reproduce**
The following example errors:
```js
const { Client } = require('hazelcast-client');

(async () => {
    const client = await Client.newHazelcastClient();

    const lock = await client.getCPSubsystem().getLock('my-lock');

    for (let i = 0; i < 3; i++) {
        tryAcquire(lock, i);
    }
})();

async function tryAcquire(lock, i) {
    const fence = await lock.lock();
    console.log('acquired', i, fence);
    setTimeout(() => {
        lock.unlock(fence);
    }, 1000);
}
```
The first iteration of `lock.unlock` throws this error:
```
hazelcast-client/lib/core/HazelcastError.js:375
        super(msg, cause, serverStackTrace);
        ^

LockOwnershipLostError: Client is not owner of the Lock[my-lock] because its Session[1] was closed by server!
    at new LockOwnershipLostError (hazelcast-client/lib/core/HazelcastError.js:375:9)
    at FencedLockProxy.newLockOwnershipLostError (hazelcast-client/lib/proxy/cpsubsystem/FencedLockProxy.js:177:16)
    at FencedLockProxy.unlock (hazelcast-client/lib/proxy/cpsubsystem/FencedLockProxy.js:125:40)
    at Timeout._onTimeout (test.js:20:14)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  cause: undefined,
  serverStackTrace: undefined
}
```
The hazelcast logs indicate each of the attempted lock acquisitions to have their own session:
```
2021-05-16 22:51:43,742 [ INFO] [hz.vibrant_gagarin.priority-generic-operation.thread-0] [c.h.c.i.p.t.AuthenticationMessageTask]: [172.17.0.2]:5701 [dev] [5.0-SNAPSHOT] Received auth from Connection[id=45, /172.17.0.2:5701->/172.17.0.1:37856, qualifier=null, endpoint=[172.17.0.1]:37856, alive=true, connectionType=NJS, planeIndex=-1], successfully authenticated, clientUuid: 614e9ba8-c389-2576-0210-be0967ab598a, client version: 4.1.0
2021-05-16 22:51:43,753 [ INFO] [hz.vibrant_gagarin.partition-operation.thread-2] [c.h.c.i.s.RaftSessionService]: [172.17.0.2]:5701 [dev] [5.0-SNAPSHOT] Created new session: 1 in CPGroupId{name='my-lock', seed=0, groupId=34} for CLIENT -> [172.17.0.1]:37856
2021-05-16 22:51:43,753 [ INFO] [hz.vibrant_gagarin.partition-operation.thread-2] [c.h.c.i.s.RaftSessionService]: [172.17.0.2]:5701 [dev] [5.0-SNAPSHOT] Created new session: 2 in CPGroupId{name='my-lock', seed=0, groupId=34} for CLIENT -> [172.17.0.1]:37856
2021-05-16 22:51:43,753 [ INFO] [hz.vibrant_gagarin.partition-operation.thread-2] [c.h.c.i.s.RaftSessionService]: [172.17.0.2]:5701 [dev] [5.0-SNAPSHOT] Created new session: 3 in CPGroupId{name='my-lock', seed=0, groupId=34} for CLIENT -> [172.17.0.1]:37856
2021-05-16 22:51:44,760 [ INFO] [hz.vibrant_gagarin.IO.thread-in-2] [c.h.i.s.t.TcpServerConnection]: [172.17.0.2]:5701 [dev] [5.0-SNAPSHOT] Connection[id=45, /172.17.0.2:5701->/172.17.0.1:37856, qualifier=null, endpoint=[172.17.0.1]:37856, alive=false, connectionType=NJS, planeIndex=-1] closed. Reason: Connection closed by the other side
2021-05-16 22:51:44,761 [ INFO] [hz.vibrant_gagarin.event-1] [c.h.c.i.ClientEndpointManager]: [172.17.0.2]:5701 [dev] [5.0-SNAPSHOT] Destroying ClientEndpoint{connection=Connection[id=45, /172.17.0.2:5701->/172.17.0.1:37856, qualifier=null, endpoint=[172.17.0.1]:37856, alive=false, connectionType=NJS, planeIndex=-1], clientUuid='614e9ba8-c389-2576-0210-be0967ab598a, authenticated=true, clientVersion=4.1.0, creationTime=1621205503742, latest clientAttributes=null, labels=[]}
```

---

When adding this snippet of code before the tryAcquire calls, the error doesn't get thrown and all of the lock acquires happen one-by-one as expected.
```js
    const initFence = await lock.lock();
    await lock.unlock(initFence);
```
When doing this, the hazelcast logs indicate only one session being used:
```
2021-05-16 22:58:22,053 [ INFO] [hz.serene_gates.priority-generic-operation.thread-0] [c.h.c.i.p.t.AuthenticationMessageTask]: [172.17.0.2]:5701 [dev] [4.2] Received auth from Connection[id=3, /172.17.0.2:5701->/172.17.0.1:37914, qualifier=null, endpoint=[172.17.0.1]:37914, alive=true, connectionType=NJS, planeIndex=-1], successfully authenticated, clientUuid: 405b7cfe-6c98-5fdd-b7b3-32d39e13a965, client version: 4.1.0
2021-05-16 22:58:22,064 [ INFO] [hz.serene_gates.partition-operation.thread-5] [c.h.c.i.s.RaftSessionService]: [172.17.0.2]:5701 [dev] [4.2] Created new session: 2 in CPGroupId{name='my-lock', seed=0, groupId=269} for CLIENT -> [172.17.0.1]:37914
2021-05-16 22:58:29,311 [ INFO] [hz.serene_gates.cached.thread-1] [c.h.c.i.ClientEndpointManager]: [172.17.0.2]:5701 [dev] [4.2] Destroying ClientEndpoint{connection=Connection[id=2, /172.17.0.2:5701->/172.17.0.1:37908, qualifier=null, endpoint=[172.17.0.1]:37908, alive=false, connectionType=NJS, planeIndex=-1], clientUuid='6a2864ca-4d24-3ffb-01ac-f8414b32d6d8, authenticated=true, clientVersion=4.1.0, creationTime=1621205890066, latest clientAttributes=null, labels=[]}
```

**Comment by aetheryx** [comment] 2021-05-16 23:58
A similar problem occurs with semaphores.
```js
const { Client } = require('hazelcast-client');

(async () => {
    const client = await Client.newHazelcastClient();

    const semaphore = await client.getCPSubsystem().getSemaphore('test-semaphore');
    await semaphore.init(3);

    for (let i = 0; i < 6; i++) {
        tryAcquire(semaphore, i);
    }
})();

async function tryAcquire(semaphore, i) {
    await semaphore.acquire(1);
    console.log('acquired', i);
    setTimeout(() => {
        semaphore.release(1);
    }, 1000);
}
```
Again, multiple sessions are used for each of the acquires, and when trying to release this error is thrown:
```
IllegalStateError: Could not release 1 permits in Semaphore[test-semaphore] because the caller has acquired less than 1 permits
```

This problem also doesn't occur by kickstarting a CP session with
```js
    await semaphore.acquire(1);
    await semaphore.release(1);
```

**Comment by srknzl** [comment] 2021-05-17 16:30
Thank you for detailed bug report. I will work on this issue as soon as I can.

**Comment by srknzl** [comment] 2021-05-20 21:09
The issue is resolved with https://github.com/hazelcast/hazelcast-nodejs-client/pull/904. 4.2 will be released at the end of this month, this change will be included in the release

**Closed** 2021-05-21 07:47 UTC
Labels: Source: Community, Type: Defect, to-jira
